# Generated by Django 4.2.11 on 2025-04-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_dict_created_by_dict_updated_by_dicttype_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.ManyToManyField(blank=True, to='system.position', verbose_name='職位'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, to='system.role', verbose_name='角色'),
        ),
    ]
