# Generated by Django 4.2.11 on 2025-04-16 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记')),
                ('name', models.CharField(max_length=100, verbose_name='橫幅名稱')),
                ('image_url', models.URLField(verbose_name='圖片URL')),
                ('link_url', models.URLField(blank=True, null=True, verbose_name='連結URL')),
                ('position', models.CharField(default='home', max_length=50, verbose_name='位置')),
                ('start_date', models.DateTimeField(verbose_name='開始日期')),
                ('end_date', models.DateTimeField(verbose_name='結束日期')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('priority', models.IntegerField(default=0, verbose_name='優先級')),
            ],
            options={
                'verbose_name': '橫幅管理',
                'verbose_name_plural': '橫幅管理',
                'db_table': 'v1_wms_banner',
                'ordering': ['-priority', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '購物車',
                'verbose_name_plural': '購物車',
                'db_table': 'v1_wms_cart',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='hot_sale_priority',
            field=models.IntegerField(default=0, verbose_name='熱銷優先級'),
        ),
        migrations.AddField(
            model_name='activity',
            name='hot_sale_subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='熱銷副標題'),
        ),
        migrations.AddField(
            model_name='activity',
            name='hot_sale_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='熱銷標題'),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_hot_sale',
            field=models.BooleanField(default=False, verbose_name='熱銷活動'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='數量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='v1.activity', verbose_name='活動')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='v1.cart', verbose_name='購物車')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '購物車項目',
                'verbose_name_plural': '購物車項目',
                'db_table': 'v1_wms_cart_item',
                'unique_together': {('cart', 'product', 'activity')},
            },
        ),
    ]
