# Generated by Django 4.2.11 on 2025-04-16 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1', '0002_banner_cart_activity_hot_sale_priority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50, unique=True, verbose_name='品號代碼')),
                ('name', models.CharField(max_length=100, verbose_name='品名')),
                ('specification', models.CharField(blank=True, max_length=100, null=True, verbose_name='規格')),
                ('unit', models.CharField(default='pcs', max_length=20, verbose_name='單位')),
                ('box_size', models.IntegerField(default=0, verbose_name='箱入數')),
                ('status', models.BooleanField(default=True, verbose_name='啟用狀態')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='建立者')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='更新者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '品號',
                'verbose_name_plural': '品號',
                'db_table': 'v1_wms_item',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='訂單編號')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='狀態')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='總金額')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='折扣金額')),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='實付金額')),
                ('payment_method', models.CharField(blank=True, max_length=20, null=True, verbose_name='付款方式')),
                ('receiver_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='收件人姓名')),
                ('receiver_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='聯絡電話')),
                ('receiver_address', models.TextField(blank=True, null=True, verbose_name='收件地址')),
                ('shipping_notes', models.TextField(blank=True, null=True, verbose_name='運輸備註')),
                ('order_notes', models.TextField(blank=True, null=True, verbose_name='訂單備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='下單用戶')),
            ],
            options={
                'verbose_name': '訂單',
                'verbose_name_plural': '訂單',
                'db_table': 'v1_wms_order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='數量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='單價')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='總價')),
                ('is_gift', models.BooleanField(default=False, verbose_name='是否為贈品')),
            ],
            options={
                'verbose_name': '訂單項目',
                'verbose_name_plural': '訂單項目',
                'db_table': 'v1_wms_order_item',
            },
        ),
        migrations.CreateModel(
            name='PromotionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记')),
                ('name', models.CharField(max_length=100, verbose_name='規則名稱')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('rule_type', models.CharField(choices=[('buy_gift', '買贈'), ('buy_discount', '買折扣'), ('order_discount', '滿額折'), ('order_free_shipping', '免運')], max_length=50, verbose_name='規則類型')),
                ('threshold_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='門檻金額')),
                ('threshold_quantity', models.IntegerField(blank=True, null=True, verbose_name='門檻數量')),
                ('discount_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='折扣比例')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='折扣金額')),
                ('is_stackable', models.BooleanField(default=False, verbose_name='是否可疊加')),
            ],
            options={
                'verbose_name': '促銷規則',
                'verbose_name_plural': '促銷規則',
                'db_table': 'v1_wms_promotion_rule',
            },
        ),
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['expiry_date', 'batch_number'], 'verbose_name': '批號', 'verbose_name_plural': '批號'},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='hot_sale_priority',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='hot_sale_subtitle',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='hot_sale_title',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='is_hot_sale',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='product',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='last_transfer_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='original_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reorder_point',
        ),
        migrations.RemoveField(
            model_name='product',
            name='safety_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specification',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_stock',
        ),
        migrations.AddField(
            model_name='activity',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='折扣金額'),
        ),
        migrations.AddField(
            model_name='activity',
            name='discount_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='折扣比例（如0.9）'),
        ),
        migrations.AddField(
            model_name='activity',
            name='discount_threshold_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='滿額門檻（元）'),
        ),
        migrations.AddField(
            model_name='activity',
            name='free_shipping',
            field=models.BooleanField(default=False, verbose_name='是否免運'),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_discount_based',
            field=models.BooleanField(default=False, verbose_name='是否為折扣型活動'),
        ),
        migrations.AddField(
            model_name='activityproduct',
            name='buy_quantity',
            field=models.IntegerField(default=1, verbose_name='購買數量門檻'),
        ),
        migrations.AddField(
            model_name='activityproduct',
            name='discount_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='商品折扣率'),
        ),
        migrations.AddField(
            model_name='activityproduct',
            name='gift_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_in_activities', to='v1.product', verbose_name='贈送商品'),
        ),
        migrations.AddField(
            model_name='activityproduct',
            name='gift_quantity',
            field=models.IntegerField(default=0, verbose_name='贈送數量'),
        ),
        migrations.AddField(
            model_name='activityproduct',
            name='is_gift_same_product',
            field=models.BooleanField(default=False, verbose_name='是否送同品項'),
        ),
        migrations.AddField(
            model_name='activityproduct',
            name='is_stackable',
            field=models.BooleanField(default=False, verbose_name='是否可與其他優惠疊加'),
        ),
        migrations.AddField(
            model_name='activityproduct',
            name='limit_per_user',
            field=models.IntegerField(blank=True, null=True, verbose_name='每人限制次數'),
        ),
        migrations.AddField(
            model_name='activityproduct',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='備註'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='建立者'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='更新者'),
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50, verbose_name='品號')),
                ('batch_number', models.CharField(max_length=50, verbose_name='批號')),
                ('quantity', models.IntegerField(verbose_name='出貨數量')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_items', to='v1.orderitem', verbose_name='訂單項目')),
            ],
            options={
                'verbose_name': '出貨明細',
                'verbose_name_plural': '出貨明細',
                'db_table': 'v1_wms_shipment_item',
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='v1.activity', verbose_name='所屬活動'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='v1.order', verbose_name='訂單'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='v1.product', verbose_name='產品'),
        ),
        migrations.AddField(
            model_name='batch',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='v1.item'),
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='參與時間')),
                ('received_gift', models.BooleanField(default=False, verbose_name='已領取贈品')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.activity', verbose_name='活動')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '使用者活動紀錄',
                'verbose_name_plural': '使用者活動紀錄',
                'db_table': 'v1_wms_user_activity_log',
                'unique_together': {('user', 'activity')},
            },
        ),
        migrations.CreateModel(
            name='ProductItemRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1, verbose_name='用量')),
                ('unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='單位')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_products', to='v1.item')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_components', to='v1.product')),
            ],
            options={
                'verbose_name': '產品-品號關聯',
                'verbose_name_plural': '產品-品號關聯',
                'db_table': 'v1_wms_product_item_relation',
                'unique_together': {('product', 'item')},
            },
        ),
    ]
