# Generated by Django 4.2.11 on 2025-04-16 08:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_item_order_orderitem_promotionrule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记')),
                ('name', models.CharField(max_length=50, verbose_name='類別名稱')),
                ('description', models.TextField(blank=True, null=True, verbose_name='類別描述')),
                ('item_count', models.IntegerField(default=0, verbose_name='品號數量')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='v1.materialcategory', verbose_name='父類別')),
            ],
            options={
                'verbose_name': '物料類別',
                'verbose_name_plural': '物料類別',
                'db_table': 'wms_material_category',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='material_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='v1.materialcategory', verbose_name='物料類別'),
        ),
    ]
