# Generated by Django 4.2.11 on 2025-04-16 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_materialcategory_item_material_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='v1_wms_category',
        ),
        migrations.AlterModelTable(
            name='materialcategory',
            table='v1_wms_material_category',
        ),
    ]
