# Generated by Django 4.2.11 on 2025-04-22 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1', '0006_historicalactivity_historicalactivityproduct_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalproductitemrelation',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical 產品-品號批號關聯', 'verbose_name_plural': 'historical 產品-品號批號關聯'},
        ),
        migrations.AlterModelOptions(
            name='productitemrelation',
            options={'verbose_name': '產品-品號批號關聯', 'verbose_name_plural': '產品-品號批號關聯'},
        ),
        migrations.AlterUniqueTogether(
            name='productitemrelation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='historicalproductitemrelation',
            name='batch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='v1.batch'),
        ),
        migrations.AddField(
            model_name='productitemrelation',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_relations', to='v1.batch'),
        ),
        migrations.AlterField(
            model_name='productitemrelation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_product_batches', to='v1.item'),
        ),
        migrations.AlterField(
            model_name='productitemrelation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_components', to='v1.product'),
        ),
        migrations.AlterUniqueTogether(
            name='productitemrelation',
            unique_together={('product', 'batch')},
        ),
        migrations.CreateModel(
            name='ProductDefaultPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='售價')),
                ('stock', models.IntegerField(default=0, verbose_name='庫存數量')),
                ('note', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='default_price', to='v1.product', verbose_name='商品')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '商品常態價格',
                'verbose_name_plural': '商品常態價格',
                'db_table': 'v1_wms_product_default_price',
            },
        ),
        migrations.CreateModel(
            name='HistoricalProductDefaultPrice',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, editable=False, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='售價')),
                ('stock', models.IntegerField(default=0, verbose_name='庫存數量')),
                ('note', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='v1.product', verbose_name='商品')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'historical 商品常態價格',
                'verbose_name_plural': 'historical 商品常態價格',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
