# Generated by Django 4.2.11 on 2025-04-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0007_alter_historicalproductitemrelation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('sitewide_discount', '全館折扣'), ('product_promotion', '商品促銷')], default='product_promotion', max_length=30),
        ),
        migrations.AddField(
            model_name='historicalactivity',
            name='activity_type',
            field=models.CharField(choices=[('sitewide_discount', '全館折扣'), ('product_promotion', '商品促銷')], default='product_promotion', max_length=30),
        ),
    ]
