# Generated by Django 4.2.11 on 2025-04-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0008_activity_activity_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityproduct',
            name='is_custom_rule',
            field=models.BooleanField(default=True, verbose_name='是否為商品自訂優惠'),
        ),
        migrations.AddField(
            model_name='historicalactivityproduct',
            name='is_custom_rule',
            field=models.BooleanField(default=True, verbose_name='是否為商品自訂優惠'),
        ),
    ]
