# Generated by Django 4.2.11 on 2025-04-23 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1', '0009_activityproduct_is_custom_rule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('sitewide_discount', '全館折扣'), ('product_promotion', '商品促銷'), ('internal_promotion', '內建單品優惠')], default='product_promotion', max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalactivity',
            name='activity_type',
            field=models.CharField(choices=[('sitewide_discount', '全館折扣'), ('product_promotion', '商品促銷'), ('internal_promotion', '內建單品優惠')], default='product_promotion', max_length=30),
        ),
        migrations.CreateModel(
            name='PromotionRuleRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记')),
                ('is_sitewide', models.BooleanField(default=False, verbose_name='是否適用全商城')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('priority', models.IntegerField(default=0, verbose_name='優先級')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_rules', to='v1.activity', verbose_name='關聯活動')),
                ('activity_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_rules', to='v1.activityproduct', verbose_name='關聯活動商品')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_rules', to='v1.product', verbose_name='關聯商品')),
                ('promotion_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='v1.promotionrule', verbose_name='促銷規則')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '促銷規則關聯',
                'verbose_name_plural': '促銷規則關聯',
                'db_table': 'v1_wms_promotion_rule_relation',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPromotionRuleRelation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, editable=False, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记')),
                ('is_sitewide', models.BooleanField(default=False, verbose_name='是否適用全商城')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('priority', models.IntegerField(default=0, verbose_name='優先級')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('activity', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='v1.activity', verbose_name='關聯活動')),
                ('activity_product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='v1.activityproduct', verbose_name='關聯活動商品')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='v1.product', verbose_name='關聯商品')),
                ('promotion_rule', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='v1.promotionrule', verbose_name='促銷規則')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'historical 促銷規則關聯',
                'verbose_name_plural': 'historical 促銷規則關聯',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
