# Generated by Django 4.2.11 on 2025-04-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0010_alter_activity_activity_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotionrulerelation',
            options={'ordering': ['-priority', 'id'], 'verbose_name': '促銷規則關聯', 'verbose_name_plural': '促銷規則關聯'},
        ),
        migrations.AlterField(
            model_name='historicalpromotionrulerelation',
            name='priority',
            field=models.IntegerField(default=0, help_text='數字越高優先級越高，用於多重規則排序', verbose_name='優先級'),
        ),
        migrations.AlterField(
            model_name='promotionrulerelation',
            name='priority',
            field=models.IntegerField(default=0, help_text='數字越高優先級越高，用於多重規則排序', verbose_name='優先級'),
        ),
    ]
