# Generated by Django 4.2.11 on 2025-04-24 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0011_alter_promotionrulerelation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='discount_rate',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='discount_threshold_amount',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='free_shipping',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='is_discount_based',
        ),
        migrations.RemoveField(
            model_name='activityproduct',
            name='buy_quantity',
        ),
        migrations.RemoveField(
            model_name='activityproduct',
            name='discount_rate',
        ),
        migrations.RemoveField(
            model_name='activityproduct',
            name='gift_product',
        ),
        migrations.RemoveField(
            model_name='activityproduct',
            name='gift_quantity',
        ),
        migrations.RemoveField(
            model_name='activityproduct',
            name='is_custom_rule',
        ),
        migrations.RemoveField(
            model_name='activityproduct',
            name='is_gift_same_product',
        ),
        migrations.RemoveField(
            model_name='activityproduct',
            name='is_stackable',
        ),
        migrations.RemoveField(
            model_name='activityproduct',
            name='limit_per_user',
        ),
        migrations.RemoveField(
            model_name='historicalactivity',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='historicalactivity',
            name='discount_rate',
        ),
        migrations.RemoveField(
            model_name='historicalactivity',
            name='discount_threshold_amount',
        ),
        migrations.RemoveField(
            model_name='historicalactivity',
            name='free_shipping',
        ),
        migrations.RemoveField(
            model_name='historicalactivity',
            name='is_discount_based',
        ),
        migrations.RemoveField(
            model_name='historicalactivityproduct',
            name='buy_quantity',
        ),
        migrations.RemoveField(
            model_name='historicalactivityproduct',
            name='discount_rate',
        ),
        migrations.RemoveField(
            model_name='historicalactivityproduct',
            name='gift_product',
        ),
        migrations.RemoveField(
            model_name='historicalactivityproduct',
            name='gift_quantity',
        ),
        migrations.RemoveField(
            model_name='historicalactivityproduct',
            name='is_custom_rule',
        ),
        migrations.RemoveField(
            model_name='historicalactivityproduct',
            name='is_gift_same_product',
        ),
        migrations.RemoveField(
            model_name='historicalactivityproduct',
            name='is_stackable',
        ),
        migrations.RemoveField(
            model_name='historicalactivityproduct',
            name='limit_per_user',
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='can_be_gift',
            field=models.BooleanField(default=False, help_text='標記此商品是否可以作為促銷活動的贈品', verbose_name='可作為贈品'),
        ),
        migrations.AddField(
            model_name='historicalpromotionrule',
            name='gift_product',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='買贈活動中贈送的商品', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='v1.product', verbose_name='贈送商品'),
        ),
        migrations.AddField(
            model_name='historicalpromotionrule',
            name='gift_quantity',
            field=models.IntegerField(blank=True, default=1, help_text='買贈活動中贈送的商品數量', null=True, verbose_name='贈送數量'),
        ),
        migrations.AddField(
            model_name='historicalpromotionrule',
            name='is_gift_same_product',
            field=models.BooleanField(default=False, verbose_name='是否為贈品同商品'),
        ),
        migrations.AddField(
            model_name='historicalpromotionrule',
            name='limit_per_user',
            field=models.IntegerField(blank=True, null=True, verbose_name='每人限制次數'),
        ),
        migrations.AddField(
            model_name='product',
            name='can_be_gift',
            field=models.BooleanField(default=False, help_text='標記此商品是否可以作為促銷活動的贈品', verbose_name='可作為贈品'),
        ),
        migrations.AddField(
            model_name='promotionrule',
            name='gift_product',
            field=models.ForeignKey(blank=True, help_text='買贈活動中贈送的商品', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_gifts', to='v1.product', verbose_name='贈送商品'),
        ),
        migrations.AddField(
            model_name='promotionrule',
            name='gift_quantity',
            field=models.IntegerField(blank=True, default=1, help_text='買贈活動中贈送的商品數量', null=True, verbose_name='贈送數量'),
        ),
        migrations.AddField(
            model_name='promotionrule',
            name='is_gift_same_product',
            field=models.BooleanField(default=False, verbose_name='是否為贈品同商品'),
        ),
        migrations.AddField(
            model_name='promotionrule',
            name='limit_per_user',
            field=models.IntegerField(blank=True, null=True, verbose_name='每人限制次數'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('sitewide_discount', '全館折扣'), ('product_promotion', '商品促銷'), ('internal_promotion', '內建單品優惠')], default='product_promotion', max_length=30, verbose_name='活動類型'),
        ),
        migrations.AlterField(
            model_name='historicalactivity',
            name='activity_type',
            field=models.CharField(choices=[('sitewide_discount', '全館折扣'), ('product_promotion', '商品促銷'), ('internal_promotion', '內建單品優惠')], default='product_promotion', max_length=30, verbose_name='活動類型'),
        ),
    ]
