# Generated by Django 4.2.11 on 2025-04-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0012_remove_activity_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='tags',
            field=models.TextField(blank=True, null=True, verbose_name='注意事項'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.TextField(blank=True, null=True, verbose_name='注意事項'),
        ),
    ]
