# Generated by Django 4.2.11 on 2025-04-30 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1', '0013_alter_historicalproduct_tags_alter_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='reserved_stock',
            field=models.IntegerField(default=0, verbose_name='預留庫存'),
        ),
        migrations.AddField(
            model_name='historicalbatch',
            name='reserved_stock',
            field=models.IntegerField(default=0, verbose_name='預留庫存'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='取消時間'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成時間'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='lock_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='訂單鎖識別碼'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='付款時間'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='payment_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='付款截止時間'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='取消時間'),
        ),
        migrations.AddField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成時間'),
        ),
        migrations.AddField(
            model_name='order',
            name='lock_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='訂單鎖識別碼'),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='付款時間'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='付款截止時間'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='status',
            field=models.CharField(choices=[('pending_payment', '待付款'), ('paid', '已付款'), ('completed', '已完成'), ('cancelled', '已取消'), ('expired', '已逾期')], default='pending_payment', max_length=20, verbose_name='狀態'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', '待付款'), ('paid', '已付款'), ('completed', '已完成'), ('cancelled', '已取消'), ('expired', '已逾期')], default='pending_payment', max_length=20, verbose_name='狀態'),
        ),
        migrations.CreateModel(
            name='OrderInventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记')),
                ('operation', models.CharField(choices=[('reserve', '預留庫存'), ('confirm', '確認扣除'), ('release', '釋放庫存')], max_length=20, verbose_name='操作類型')),
                ('quantity', models.IntegerField(verbose_name='數量')),
                ('note', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.batch', verbose_name='批號')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='v1.order', verbose_name='訂單')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '訂單庫存日誌',
                'verbose_name_plural': '訂單庫存日誌',
                'db_table': 'v1_wms_order_inventory_log',
            },
        ),
        migrations.CreateModel(
            name='OrderConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记')),
                ('payment_timeout_minutes', models.IntegerField(default=30, verbose_name='付款超時時間(分鐘)')),
                ('inventory_lock_seconds', models.IntegerField(default=180, verbose_name='庫存鎖定時間(秒)')),
                ('auto_cancel_enabled', models.BooleanField(default=True, verbose_name='啟用自動取消功能')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '訂單設定',
                'verbose_name_plural': '訂單設定',
                'db_table': 'v1_wms_order_configuration',
            },
        ),
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记')),
                ('quantity', models.IntegerField(verbose_name='預留數量')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='是否確認')),
                ('expires_at', models.DateTimeField(null=True, verbose_name='預留過期時間')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='v1.batch', verbose_name='批號')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.item', verbose_name='品號')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_reservations', to='v1.order', verbose_name='訂單')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '庫存預留',
                'verbose_name_plural': '庫存預留',
                'db_table': 'v1_wms_inventory_reservation',
            },
        ),
        migrations.CreateModel(
            name='HistoricalOrderInventoryLog',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, editable=False, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记')),
                ('operation', models.CharField(choices=[('reserve', '預留庫存'), ('confirm', '確認扣除'), ('release', '釋放庫存')], max_length=20, verbose_name='操作類型')),
                ('quantity', models.IntegerField(verbose_name='數量')),
                ('note', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('batch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='v1.batch', verbose_name='批號')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='v1.order', verbose_name='訂單')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'historical 訂單庫存日誌',
                'verbose_name_plural': 'historical 訂單庫存日誌',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOrderConfiguration',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, editable=False, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记')),
                ('payment_timeout_minutes', models.IntegerField(default=30, verbose_name='付款超時時間(分鐘)')),
                ('inventory_lock_seconds', models.IntegerField(default=180, verbose_name='庫存鎖定時間(秒)')),
                ('auto_cancel_enabled', models.BooleanField(default=True, verbose_name='啟用自動取消功能')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'historical 訂單設定',
                'verbose_name_plural': 'historical 訂單設定',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalInventoryReservation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, editable=False, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记')),
                ('quantity', models.IntegerField(verbose_name='預留數量')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='是否確認')),
                ('expires_at', models.DateTimeField(null=True, verbose_name='預留過期時間')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('batch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='v1.batch', verbose_name='批號')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='v1.item', verbose_name='品號')),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='v1.order', verbose_name='訂單')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'historical 庫存預留',
                'verbose_name_plural': 'historical 庫存預留',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
