from .warehouse import (
    MaterialCategorySerializer,
    MaterialCategoryTreeSerializer,
    MaterialCategoryItemCountSerializer,
    CategorySerializer,
    CategoryTreeSerializer,
    ItemSerializer,
    ItemCreateUpdateSerializer,
    ProductItemRelationSerializer, 
    BatchListSerializer,
    BatchDetailSerializer,
    BatchCreateUpdateSerializer,
    InventoryReservationSerializer,
)
from .ecommerce import (
    ProductListSerializer,
    ProductDetailSerializer,
    ProductCreateUpdateSerializer,
    ProductImageSerializer,
    BannerSerializer,
    BannerResponseSerializer,
    CartItemSerializer,
    CartItemCreateSerializer,
    OrderSerializer,
    OrderItemSerializer,
    ShipmentItemSerializer,
    ProductWithPricingSerializer,
    ProductStockStatSerializer,
    CategoryProductCountSerializer,
    WarehouseStockSerializer,
    OrderInventoryLogSerializer,
)
from .promotion import (
    ActivityListSerializer,
    ActivityDetailSerializer,
    ActivityProductSerializer,
    ActivityProductCreateUpdateSerializer,
    HotSaleActivitySerializer,
    PromotionRuleSerializer,
    PromotionRuleRelationSerializer,
    UserActivityLogSerializer,
    HistoricalRecordSerializer,
    GiftProductBriefSerializer,
)

from .customer import(
    CustomerServiceConfigSerializer,
    FAQSerializer,
    CustomerServiceMessageSerializer,
    CustomerServiceRequestListSerializer,
    CustomerServiceRequestDetailSerializer,
    CustomerServiceRequestCreateSerializer,
    CustomerServiceMessageCreateSerializer,
    CustomerServiceRequestStatusUpdateSerializer,
)


__all__ = [
    # Warehouse serializers
    'MaterialCategorySerializer',
    'MaterialCategoryTreeSerializer',
    'MaterialCategoryItemCountSerializer',
    'CategorySerializer',
    'CategoryTreeSerializer',
    'ItemSerializer',
    'ItemCreateUpdateSerializer',
    'ProductItemRelationSerializer',
    'BatchListSerializer',
    'BatchDetailSerializer',
    'BatchCreateUpdateSerializer',
    'InventoryReservationSerializer',
    
    # E-commerce serializers
    'ProductListSerializer',
    'ProductDetailSerializer',
    'ProductCreateUpdateSerializer',
    'ProductImageSerializer',
    'BannerSerializer',
    'BannerResponseSerializer',
    'CartItemSerializer',
    'CartItemCreateSerializer',
    'OrderSerializer',
    'OrderItemSerializer',
    'ShipmentItemSerializer',
    'ProductWithPricingSerializer',
    'ProductStockStatSerializer',
    'CategoryProductCountSerializer',
    'WarehouseStockSerializer',
    'OrderInventoryLogSerializer',
    
    # Promotion serializers
    'ActivityListSerializer',
    'ActivityDetailSerializer',
    'ActivityProductSerializer',
    'ActivityProductCreateUpdateSerializer',
    'HotSaleActivitySerializer',
    'PromotionRuleSerializer',
    'PromotionRuleRelationSerializer',
    'UserActivityLogSerializer',
    'HistoricalRecordSerializer',
    'GiftProductBriefSerializer',


    'CustomerServiceConfigSerializer',
    'FAQSerializer',
    'CustomerServiceMessageSerializer',
    'CustomerServiceRequestListSerializer',
    'CustomerServiceRequestDetailSerializer',
    'CustomerServiceRequestCreateSerializer',
    'CustomerServiceMessageCreateSerializer',
    'CustomerServiceRequestStatusUpdateSerializer',
]